import {
  CompanySector,
  Country,
  DealCompanyRole,
  DealSubtype,
  DealType,
  ProjectSector,
  Region,
  Sector,
  SubSector,
  Technology,
} from "./types";
import {
  companySector,
  projectSector,
  companySubSector,
  projectSubSector,
} from "./db/schema";

export const LOCALE_KEY = "akili-language";

export const DEFAULT_PAGE_SIZE = 10;
export const BLOG_PAGE_SIZE = 6;
export const NEWS_PAGE_SIZE = 4;
export const RESEARCH_PAGE_SIZE = 3;

export const IMAGE_BUCKET = "images";

export const PROJECT_COMPANY_ROLES = [
  "special_purpose_vehicle",
  "sponsor",
  "contractor",
  "operations_maintenance",
  "equipment_supplier",
  "lender",
  "advisor",
  "grid_operator",
  "procurement_officer",
  "tender_winner",
];

export const REGIONS_COUNTRIES: Record<Region, Country[]> = {
  north_africa: ["DZ", "EG", "LY", "MA", "SD", "TN", "EH"],
  central_africa: ["AO", "CM", "CF", "TD", "CG", "CD", "GQ", "GA", "ST"],
  west_africa: [
    "BJ",
    "BF",
    "CV",
    "CI",
    "GM",
    "GH",
    "GN",
    "GW",
    "LR",
    "ML",
    "MR",
    "NE",
    "NG",
    "SN",
    "SL",
    "TG",
  ],
  east_africa: [
    "BI",
    "KM",
    "DJ",
    "ER",
    "ET",
    "KE",
    "MG",
    "MW",
    "MU",
    "YT",
    "MZ",
    "RE",
    "RW",
    "SC",
    "SO",
    "SS",
    "TZ",
    "UG",
    "ZM",
    "ZW",
  ],
  southern_africa: ["BW", "LS", "NA", "ZA", "SZ"],
};

export const SECTORS: Sector[] = [
  ...new Set([...companySector.enumValues, ...projectSector.enumValues]),
];
export const SECTORS_TECHNOLOGIES: Partial<Record<Sector, Technology[]>> = {
  solar: [
    "photovoltaic",
    "concentrated_solar_power",
    "solar_home_systems",
    "concentrated_photovoltaic",
  ],
  wind: ["onshore_wind", "offshore_wind"],
  hydro: ["small_hydro", "large_hydro"],
  battery: ["bess", "lithium_ion"],
  biomass: ["biogas", "waste"],
  oil_gas: ["oil", "gas", "coal"],
  utilities: ["mini_grid", "decentralised", "high_voltage_transmission_lines"],
  hydrogen: ["hydrogen"],
  geothermal: ["geothermal"],
  nuclear: ["nuclear"],
};
export const SUB_SECTORS: SubSector[] = [
  ...companySubSector.enumValues,
  ...projectSubSector.enumValues,
];

export const DEAL_TYPES_SUBTYPES: Record<DealType, DealSubtype[]> = {
  merger_acquisition: ["asset", "ma_corporate"],
  financing: ["debt", "equity", "grant"],
  power_purchase_agreement: ["utility", "ppa_corporate"],
  joint_venture: [
    "joint_venture",
    "strategic_partnership_agreement",
    "strategic_collaboration",
  ],
  project_update: [
    "early_stage",
    "late_stage",
    "ready_to_build",
    "in_construction",
    "operational",
    "proposal",
  ],
};

export const DEAL_COMPANY_ROLES: Record<DealType, DealCompanyRole[]> = {
  merger_acquisition: [
    "offtaker",
    "buyer",
    "seller",
    "advisor",
    "financial_advisor",
    "technical_advisor",
    "legal_advisor",
    "lead_arranger",
  ],
  financing: [
    "investor",
    "advisor",
    "financial_advisor",
    "technical_advisor",
    "legal_advisor",
  ],
  power_purchase_agreement: [],
  joint_venture: [],
  project_update: [],
};

export const DEAL_ADVISORS = [
  "advisor",
  "legal_advisor",
  "financial_advisor",
  "technical_advisor",
];

export const ISO_3166 = [
  "AD",
  "AE",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AO",
  "AQ",
  "AR",
  "AS",
  "AT",
  "AU",
  "AW",
  "AX",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BL",
  "BM",
  "BN",
  "BO",
  "BQ",
  "BR",
  "BS",
  "BT",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CC",
  "CD",
  "CF",
  "CG",
  "CH",
  "CI",
  "CK",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CW",
  "CX",
  "CY",
  "CZ",
  "DE",
  "DJ",
  "DK",
  "DM",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "EH",
  "ER",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FK",
  "FM",
  "FO",
  "FR",
  "GA",
  "GB",
  "GD",
  "GE",
  "GF",
  "GG",
  "GH",
  "GI",
  "GL",
  "GM",
  "GN",
  "GP",
  "GQ",
  "GR",
  "GS",
  "GT",
  "GU",
  "GW",
  "GY",
  "HK",
  "HM",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IM",
  "IN",
  "IO",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JE",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KI",
  "KM",
  "KN",
  "KP",
  "KR",
  "KW",
  "KY",
  "KZ",
  "LA",
  "LB",
  "LC",
  "LI",
  "LK",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MC",
  "MD",
  "ME",
  "MF",
  "MG",
  "MH",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MP",
  "MQ",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NC",
  "NE",
  "NF",
  "NG",
  "NI",
  "NL",
  "NO",
  "NP",
  "NR",
  "NU",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PF",
  "PG",
  "PH",
  "PK",
  "PL",
  "PM",
  "PN",
  "PR",
  "PS",
  "PT",
  "PW",
  "PY",
  "QA",
  "RE",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SD",
  "SE",
  "SG",
  "SH",
  "SI",
  "SJ",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SR",
  "SS",
  "ST",
  "SV",
  "SX",
  "SY",
  "SZ",
  "TC",
  "TD",
  "TF",
  "TG",
  "TH",
  "TJ",
  "TK",
  "TL",
  "TM",
  "TN",
  "TO",
  "TR",
  "TT",
  "TV",
  "TW",
  "TZ",
  "UA",
  "UG",
  "UM",
  "US",
  "UY",
  "UZ",
  "VA",
  "VC",
  "VE",
  "VG",
  "VI",
  "VN",
  "VU",
  "WF",
  "WS",
  "YE",
  "YT",
  "ZA",
  "ZM",
  "ZW",
];

export const COUNTRIES_ISO_3166_CODE: Record<string, Uppercase<string>> = {
  // A
  afghanistan: "AF",
  albania: "AL",
  albanie: "AL",
  algeria: "DZ",
  algérie: "DZ",
  andorra: "AD",
  andorre: "AD",
  angola: "AO",
  "antigua and barbuda": "AG",
  "antigua-et-barbuda": "AG",
  argentina: "AR",
  argentine: "AR",
  armenia: "AM",
  arménie: "AM",
  australia: "AU",
  australie: "AU",
  austria: "AT",
  autriche: "AT",
  azerbaijan: "AZ",
  azerbaïdjan: "AZ",
  // B
  bahamas: "BS",
  bahrain: "BH",
  bahreïn: "BH",
  bangladesh: "BD",
  barbados: "BB",
  barbade: "BB",
  belarus: "BY",
  bélarus: "BY",
  belgium: "BE",
  belgique: "BE",
  belize: "BZ",
  bélize: "BZ",
  benin: "BJ",
  bénin: "BJ",
  bhutan: "BT",
  bhoutan: "BT",
  bolivia: "BO",
  bolivie: "BO",
  "bosnia and herzegovina": "BA",
  "bosnie-herzégovine": "BA",
  botswana: "BW",
  brazil: "BR",
  brésil: "BR",
  brunei: "BN",
  bulgaria: "BG",
  bulgarie: "BG",
  "burkina faso": "BF",
  burundi: "BI",
  // C
  "cabo verde": "CV",
  "cape verde": "CV",
  "cap-vert": "CV",
  cambodia: "KH",
  cambodge: "KH",
  cameroon: "CM",
  cameroun: "CM",
  canada: "CA",
  "central african republic": "CF",
  "république centrafricaine": "CF",
  chad: "TD",
  tchad: "TD",
  chile: "CL",
  chili: "CL",
  china: "CN",
  chine: "CN",
  colombia: "CO",
  colombie: "CO",
  comoros: "KM",
  comores: "KM",
  congo: "CG",
  "congo, republic of": "CG",
  "republic of congo": "CG",
  "congo-brazzaville": "CG",
  "democratic republic of congo": "CD",
  "congo, république démocratique": "CD",
  "république démocratique du congo": "CD",
  "congo-kinshasa": "CD",
  drc: "CD",
  rdc: "CD",
  "cook islands": "CK",
  "îles cook": "CK",
  "costa rica": "CR",
  "côte d'ivoire": "CI",
  "cote d'ivoire": "CI",
  "ivory coast": "CI",
  croatia: "HR",
  croatie: "HR",
  cuba: "CU",
  cyprus: "CY",
  chypre: "CY",
  czechia: "CZ",
  "czech republic": "CZ",
  "république tchèque": "CZ",
  tchéquie: "CZ",
  // D
  denmark: "DK",
  danemark: "DK",
  djibouti: "DJ",
  dominica: "DM",
  dominique: "DM",
  "dominican republic": "DO",
  "république dominicaine": "DO",
  // E
  ecuador: "EC",
  équateur: "EC",
  egypt: "EG",
  égypte: "EG",
  "el salvador": "SV",
  "equatorial guinea": "GQ",
  "guinée équatoriale": "GQ",
  eritrea: "ER",
  érythrée: "ER",
  estonia: "EE",
  estonie: "EE",
  eswatini: "SZ",
  swaziland: "SZ",
  ethiopia: "ET",
  éthiopie: "ET",
  // F
  fiji: "FJ",
  fidji: "FJ",
  finland: "FI",
  finlande: "FI",
  france: "FR",
  // G
  gabon: "GA",
  gambia: "GM",
  gambie: "GM",
  georgia: "GE",
  géorgie: "GE",
  germany: "DE",
  allemagne: "DE",
  ghana: "GH",
  greece: "GR",
  grèce: "GR",
  grenada: "GD",
  grenade: "GD",
  guatemala: "GT",
  guinea: "GN",
  guinée: "GN",
  "guinea-bissau": "GW",
  "guinée-bissau": "GW",
  guyana: "GY",
  // H
  haiti: "HT",
  haïti: "HT",
  honduras: "HN",
  hungary: "HU",
  hongrie: "HU",
  // I
  iceland: "IS",
  islande: "IS",
  india: "IN",
  inde: "IN",
  indonesia: "ID",
  indonésie: "ID",
  iran: "IR",
  iraq: "IQ",
  ireland: "IE",
  irlande: "IE",
  israel: "IL",
  israël: "IL",
  italy: "IT",
  italie: "IT",
  // J
  jamaica: "JM",
  jamaïque: "JM",
  japan: "JP",
  japon: "JP",
  jordan: "JO",
  jordanie: "JO",
  // K
  kazakhstan: "KZ",
  kenya: "KE",
  kiribati: "KI",
  "north korea": "KP",
  "corée du nord": "KP",
  "south korea": "KR",
  "corée du sud": "KR",
  kosovo: "XK", // User note: XK is temporary use, RS is Serbia
  kuwait: "KW",
  koweït: "KW",
  kyrgyzstan: "KG",
  kirghizistan: "KG",
  // L
  laos: "LA",
  latvia: "LV",
  lettonie: "LV",
  lebanon: "LB",
  liban: "LB",
  lesotho: "LS",
  liberia: "LR",
  libéria: "LR",
  libya: "LY",
  libye: "LY",
  liechtenstein: "LI",
  lithuania: "LT",
  lituanie: "LT",
  luxembourg: "LU",
  // M
  madagascar: "MG",
  malawi: "MW",
  malaysia: "MY",
  malaisie: "MY",
  maldives: "MV",
  mali: "ML",
  malta: "MT",
  malte: "MT",
  "marshall islands": "MH",
  "îles marshall": "MH",
  mauritania: "MR",
  mauritanie: "MR",
  mauritius: "MU",
  "île maurice": "MU",
  mayotte: "YT",
  mexico: "MX",
  mexique: "MX",
  micronesia: "FM",
  micronésie: "FM",
  moldova: "MD",
  monaco: "MC",
  mongolia: "MN",
  mongolie: "MN",
  montenegro: "ME",
  monténégro: "ME",
  morocco: "MA",
  maroc: "MA",
  mozambique: "MZ",
  myanmar: "MM",
  birmanie: "MM",
  // N
  namibia: "NA",
  namibie: "NA",
  nauru: "NR",
  nepal: "NP",
  népal: "NP",
  netherlands: "NL",
  "pays-bas": "NL",
  "new zealand": "NZ",
  "nouvelle-zélande": "NZ",
  nicaragua: "NI",
  niger: "NE",
  nigeria: "NG",
  niue: "NU",
  nioué: "NU",
  "north macedonia": "MK",
  "macédoine du nord": "MK",
  norway: "NO",
  norvège: "NO",
  // O
  oman: "OM",
  // P
  pakistan: "PK",
  palau: "PW",
  palaos: "PW",
  palestine: "PS",
  panama: "PA",
  "papua new guinea": "PG",
  "papouasie-nouvelle-guinée": "PG",
  paraguay: "PY",
  peru: "PE",
  pérou: "PE",
  philippines: "PH",
  poland: "PL",
  pologne: "PL",
  portugal: "PT",
  // Q
  qatar: "QA",
  // R
  reunion: "RE",
  réunion: "RE",
  romania: "RO",
  roumanie: "RO",
  russia: "RU",
  russie: "RU",
  rwanda: "RW",
  // S
  "saint kitts and nevis": "KN",
  "saint-kitts-et-nevis": "KN",
  "saint lucia": "LC",
  "sainte-lucie": "LC",
  "saint vincent and the grenadines": "VC",
  "saint-vincent-et-les-grenadines": "VC",
  samoa: "WS",
  "san marino": "SM",
  "saint-marin": "SM",
  "sao tome and principe": "ST",
  "são tomé and príncipe": "ST",
  "sao tomé-et-principe": "ST",
  "saudi arabia": "SA",
  "arabie saoudite": "SA",
  senegal: "SN",
  sénégal: "SN",
  serbia: "RS",
  serbie: "RS",
  seychelles: "SC",
  "sierra leone": "SL",
  singapore: "SG",
  singapour: "SG",
  slovakia: "SK",
  slovaquie: "SK",
  slovenia: "SI",
  slovénie: "SI",
  "solomon islands": "SB",
  "îles salomon": "SB",
  somalia: "SO",
  somalie: "SO",
  "south africa": "ZA",
  "afrique du sud": "ZA",
  "south sudan": "SS",
  "soudan du sud": "SS",
  spain: "ES",
  espagne: "ES",
  "sri lanka": "LK",
  sudan: "SD",
  soudan: "SD",
  suriname: "SR",
  sweden: "SE",
  suède: "SE",
  switzerland: "CH",
  suisse: "CH",
  syria: "SY",
  syrie: "SY",
  // T
  taiwan: "TW",
  tajikistan: "TJ",
  tadjikistan: "TJ",
  tanzania: "TZ",
  tanzanie: "TZ",
  thailand: "TH",
  thaïlande: "TH",
  "timor-leste": "TL",
  togo: "TG",
  tonga: "TO",
  "trinidad and tobago": "TT",
  "trinité-et-tobago": "TT",
  tunisia: "TN",
  tunisie: "TN",
  turkey: "TR",
  turquie: "TR",
  turkmenistan: "TM",
  turkménistan: "TM",
  tuvalu: "TV",
  // U
  uganda: "UG",
  ouganda: "UG",
  ukraine: "UA",
  "united arab emirates": "AE",
  "émirats arabes unis": "AE",
  uae: "AE",
  "united kingdom": "GB",
  "royaume-uni": "GB",
  uk: "GB",
  "great britain": "GB",
  "united states": "US",
  "états-unis": "US",
  usa: "US",
  us: "US",
  uruguay: "UY",
  uzbekistan: "UZ",
  ouzbekistan: "UZ",
  // V
  vanuatu: "VU",
  "vatican city": "VA",
  "cité du vatican": "VA",
  vatican: "VA",
  venezuela: "VE",
  vietnam: "VN",
  "viet nam": "VN",
  // W
  "western sahara": "EH",
  "sahara occidental": "EH",
  // Y
  yemen: "YE",
  yémen: "YE",
  // Z
  zambia: "ZM",
  zambie: "ZM",
  zimbabwe: "ZW",
};

export const TECHNOLOGIES_SECTORS: Record<
  Technology,
  { projectSector: ProjectSector; companySector: CompanySector }
> = {
  photovoltaic: { projectSector: "solar", companySector: "renewables" },
  concentrated_solar_power: {
    projectSector: "solar",
    companySector: "renewables",
  },
  solar_home_systems: { projectSector: "solar", companySector: "renewables" },
  concentrated_photovoltaic: {
    projectSector: "solar",
    companySector: "renewables",
  },
  onshore_wind: { projectSector: "wind", companySector: "renewables" },
  offshore_wind: { projectSector: "wind", companySector: "renewables" },
  small_hydro: { projectSector: "hydro", companySector: "renewables" },
  large_hydro: { projectSector: "hydro", companySector: "renewables" },
  bess: { projectSector: "battery", companySector: "renewables" },
  lithium_ion: { projectSector: "battery", companySector: "renewables" },
  biogas: { projectSector: "biomass", companySector: "renewables" },
  waste: { projectSector: "biomass", companySector: "renewables" },
  oil: { projectSector: "oil_gas", companySector: "non_renewables" },
  gas: { projectSector: "oil_gas", companySector: "non_renewables" },
  coal: { projectSector: "oil_gas", companySector: "non_renewables" },
  mini_grid: { projectSector: "other", companySector: "utilities" },
  decentralised: { projectSector: "other", companySector: "utilities" },
  high_voltage_transmission_lines: {
    projectSector: "other",
    companySector: "utilities",
  },
  hydrogen: { projectSector: "hydrogen", companySector: "renewables" },
  green_hydrogen: { projectSector: "hydrogen", companySector: "renewables" },
  geothermal: { projectSector: "geothermal", companySector: "renewables" },
  nuclear: { projectSector: "nuclear", companySector: "non_renewables" },
  wave_onshore: { projectSector: "hydro", companySector: "renewables" },
  wave_nearshore: { projectSector: "hydro", companySector: "renewables" },
  hybrid: { projectSector: "other", companySector: "other" },
};
